**RAFIA RAMEEN**

**Assignment 01:** **Array Creation and manipulation**

In [10]:
import numpy as np

# Task 1: 5x5 array
arr1_1 = np.random.randint(1, 21, size=(5, 5))
print("1. Original Array:\n", arr1_1)
arr1_1[:, 2] = 1
print("Replaced 3rd column with 1:\n", arr1_1)

# Task 2: 4x4 array
arr1_2 = np.arange(1, 17).reshape(4, 4)
print("\n2. Original Array:\n", arr1_2)
np.fill_diagonal(arr1_2, 0)
print("Diagonal elements set to 0:\n", arr1_2)

1. Original Array:
 [[20 20 11 11 20]
 [ 4  1 12 13 12]
 [ 5  5 14 11 14]
 [13  3  2 10  6]
 [ 6  5  5  6  5]]
Replaced 3rd column with 1:
 [[20 20  1 11 20]
 [ 4  1  1 13 12]
 [ 5  5  1 11 14]
 [13  3  1 10  6]
 [ 6  5  1  6  5]]

2. Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements set to 0:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


**Assignment 02: Array Indexing and Slicing**

In [11]:
# Task 1:
arr2_1 = np.arange(1, 37).reshape(6, 6)
sub_arr = arr2_1[2:5, 1:4]
print("1. Extracted Sub-array:\n", sub_arr)

# Task 2:
arr2_2 = np.random.randint(1, 50, size=(5, 5))
print("\n2. Original 5x5 Array:\n", arr2_2)
top = arr2_2[0, :]
bottom = arr2_2[-1, :]
left = arr2_2[1:-1, 0]
right = arr2_2[1:-1, -1]
border_elements = np.concatenate([top, right, bottom[::-1], left[::-1]])
print("Border elements:", border_elements)

1. Extracted Sub-array:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]

2. Original 5x5 Array:
 [[35 12 49 32  8]
 [33 37  3 38 29]
 [ 3 25 25 12 41]
 [44 24 38 35 24]
 [16 23  3  9 14]]
Border elements: [35 12 49 32  8 29 41 24 14  9  3 23 16 44  3 33]


**Assignment 03: Array Operations**

In [12]:
# Task 1:
a1 = np.random.randint(1, 10, size=(3, 4))
a2 = np.random.randint(1, 10, size=(3, 4))
print("1. Addition:\n", a1 + a2)
print("Subtraction:\n", a1 - a2)
print("Multiplication:\n", a1 * a2)
print("Division:\n", a1 / a2)

# Task 2:
arr3_2 = np.arange(1, 17).reshape(4, 4)
print("\n2. Row-wise sum:", np.sum(arr3_2, axis=1))
print("Column-wise sum:", np.sum(arr3_2, axis=0))

1. Addition:
 [[ 9  8 14  7]
 [ 5  5 13  7]
 [ 6 13 11  3]]
Subtraction:
 [[-5 -6  0  5]
 [-3 -1 -1 -5]
 [ 0  3  7  1]]
Multiplication:
 [[14  7 49  6]
 [ 4  6 42  6]
 [ 9 40 18  2]]
Division:
 [[0.28571429 0.14285714 1.         6.        ]
 [0.25       0.66666667 0.85714286 0.16666667]
 [1.         1.6        4.5        2.        ]]

2. Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


**Assignment 04: Statistical operations**

In [13]:
# Task 1:
arr4_1 = np.random.randint(1, 100, size=(5, 5))
print("1. Mean:", np.mean(arr4_1))
print("Median:", np.median(arr4_1))
print("Standard Deviation:", np.std(arr4_1))
print("Variance:", np.var(arr4_1))

# Task 2:
arr4_2 = np.arange(1, 10).reshape(3, 3)
normalized = (arr4_2 - np.mean(arr4_2)) / np.std(arr4_2)
print("\n2. Normalized Array (Mean=0, Std=1):\n", normalized)

1. Mean: 47.84
Median: 47.0
Standard Deviation: 28.899384076481635
Variance: 835.1744000000002

2. Normalized Array (Mean=0, Std=1):
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


**Assignment 05: Broadcasting**

In [14]:
# Task 1:
arr5_1_2d = np.random.randint(1, 10, size=(3, 3))
arr5_1_1d = np.array([1, 2, 3])
print("1. Row Broadcasting Result:\n", arr5_1_2d + arr5_1_1d)

# Task 2:
arr5_2_2d = np.random.randint(1, 10, size=(4, 4))
arr5_2_1d = np.array([1, 2, 3, 4]).reshape(4, 1)
print("\n2. Column Broadcasting Result:\n", arr5_2_2d - arr5_2_1d)

1. Row Broadcasting Result:
 [[8 7 6]
 [5 6 9]
 [3 3 7]]

2. Column Broadcasting Result:
 [[ 1  1  2  2]
 [ 3  4  5 -1]
 [ 5 -1  3  6]
 [ 1  1  5  3]]


**Assignment 06: Linear Algebra**

In [15]:
# Task 1:
matrix = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
print("1. Determinant:", np.linalg.det(matrix))
print("Inverse:\n", np.linalg.inv(matrix))
eigenvalues, _ = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)

# Task 2:
m1 = np.random.randint(1, 10, size=(2, 3))
m2 = np.random.randint(1, 10, size=(3, 2))
print("\n2. Matrix Multiplication Result:\n", np.dot(m1, m2))

1. Determinant: -1.0
Inverse:
 [[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]
Eigenvalues: [ 3.91222918  1.28646207 -0.19869124]

2. Matrix Multiplication Result:
 [[ 82  81]
 [104 113]]


**Assignment 07: Advanced array manipulation**

In [16]:
# Task 1:
arr7_1 = np.arange(1, 10).reshape(3, 3)
print("1. Reshaped to (1, 9):\n", arr7_1.reshape(1, 9))
print("Reshaped to (9, 1):\n", arr7_1.reshape(9, 1))

# Task 2:
arr7_2 = np.random.randint(1, 20, size=(5, 5))
flattened = arr7_2.flatten()
print("\n2. Flattened array:", flattened)
print("Reshaped back to (5, 5):\n", flattened.reshape(5, 5))

1. Reshaped to (1, 9):
 [[1 2 3 4 5 6 7 8 9]]
Reshaped to (9, 1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

2. Flattened array: [14 18  6  9 12  1  9  9 14  6 15  1 14  8 15 10 18 18  4  1 16 14  4 16
  6]
Reshaped back to (5, 5):
 [[14 18  6  9 12]
 [ 1  9  9 14  6]
 [15  1 14  8 15]
 [10 18 18  4  1]
 [16 14  4 16  6]]


**Assignment 08: Fancy Indexing and Boolean Indexing**

In [17]:
# Task 1:
arr8_1 = np.random.randint(1, 50, size=(5, 5))
print("1. Original Array:\n", arr8_1)
corners = arr8_1[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:", corners)

# Task 2:
arr8_2 = np.random.randint(1, 20, size=(4, 4))
print("\n2. Original Array:\n", arr8_2)
arr8_2[arr8_2 > 10] = 10
print("Array after setting elements > 10 to 10:\n", arr8_2)

1. Original Array:
 [[ 5  5 13 49 26]
 [30 28  7 41 43]
 [21 24  3 41  7]
 [37 48  8  9  5]
 [41 32 16 15 40]]
Corner elements: [ 5 26 41 40]

2. Original Array:
 [[13 16  3  8]
 [15  8 18  1]
 [ 6  1 14  2]
 [ 1  4  8  5]]
Array after setting elements > 10 to 10:
 [[10 10  3  8]
 [10  8 10  1]
 [ 6  1 10  2]
 [ 1  4  8  5]]


**Assignment 09: Structured Arrays**

In [18]:
# Task 1:
dtype1 = [('name', 'S10'), ('age', int), ('weight', float)]
data1 = np.array([('Alice', 25, 55.5), ('Bob', 20, 68.0), ('Charlie', 30, 72.3)], dtype=dtype1)
print("1. Sorted by Age:\n", np.sort(data1, order='age'))

# Task 2:
dtype2 = [('x', int), ('y', int)]
pts = np.array([(1, 2), (4, 6)], dtype=dtype2)
dist = np.sqrt((pts['x'][0] - pts['x'][1])**2 + (pts['y'][0] - pts['y'][1])**2)
print("\n2. Euclidean distance:", dist)

1. Sorted by Age:
 [(b'Bob', 20, 68. ) (b'Alice', 25, 55.5) (b'Charlie', 30, 72.3)]

2. Euclidean distance: 5.0


**Assignment 10: Masked Arrays**

In [19]:
# Task 1:
arr10_1 = np.random.randint(1, 20, size=(4, 4))
masked_arr1 = np.ma.masked_greater(arr10_1, 10)
print("1. Masked Array (>10):\n", masked_arr1)
print("Sum of unmasked elements:", masked_arr1.sum())

# Task 2:
arr10_2 = np.random.randint(1, 20, size=(3, 3)).astype(float)
mask = np.eye(3, dtype=bool)
masked_arr2 = np.ma.array(arr10_2, mask=mask)
arr10_2[mask] = masked_arr2.mean()
print("\n2. Array with diagonal replaced by unmasked mean:\n", arr10_2)

1. Masked Array (>10):
 [[7 5 7 --]
 [4 2 -- --]
 [6 -- 1 10]
 [9 4 3 6]]
Sum of unmasked elements: 64

2. Array with diagonal replaced by unmasked mean:
 [[12. 18.  3.]
 [15. 12. 15.]
 [ 3. 18. 12.]]
