Task1

In [5]:
import numpy as np

arr = np.random.randint(1,21, size = (5,5))
arr[:,2] = 1
print(arr)

[[ 8 13  1 14 13]
 [ 7 15  1  7 13]
 [14  8  1 13 16]
 [11  4  1 11  3]
 [10 14  1  4 17]]


In [ ]:
arr1 = np.arange(1,17).reshape((4,4))
np.fill_diagonal(arr1,0)
print(arr1)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


#Task2

In [18]:
arr2 = np.arange(1,37).reshape(6,6)
print(arr2)
sub = arr2[2:5, 1:4]
print(sub)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [19]:
arr = np.random.randint(1, 50, size=(5, 5))
border = np.concatenate([arr[0, :],      # top row
                         arr[-1, :],     # bottom row
                         arr[1:-1, 0],   # left column (without corners)
                         arr[1:-1, -1]]) # right column (without corners)
print(arr)
print("Border:", border)

[[11 11 31 48 10]
 [32 25  6 44  8]
 [ 3 38 36 35 17]
 [10 39  1  2 20]
 [20 42 30  5 48]]
Border: [11 11 31 48 10 20 42 30  5 48 32  3 10  8 17 20]


Task3

In [22]:
arr1 = np.random.randint(1,10, size = (3,4))
arr2 = np.random.randint(10,20, size = (3,4))

print(arr1)
print(arr2)

add = np.add(arr1,arr2)
sub  = np.subtract(arr1,arr2)
mult  = np.multiply(arr1,arr2)
div  = np.divide(arr1,arr2)

print(add) 
print(sub)
print (mult) 
print(div)



[[1 5 9 5]
 [6 6 7 3]
 [4 9 1 1]]
[[18 11 15 18]
 [10 19 11 18]
 [13 18 10 19]]
[[19 16 24 23]
 [16 25 18 21]
 [17 27 11 20]]
[[-17  -6  -6 -13]
 [ -4 -13  -4 -15]
 [ -9  -9  -9 -18]]
[[ 18  55 135  90]
 [ 60 114  77  54]
 [ 52 162  10  19]]
[[0.05555556 0.45454545 0.6        0.27777778]
 [0.6        0.31578947 0.63636364 0.16666667]
 [0.30769231 0.5        0.1        0.05263158]]


In [23]:
arr2 = np.arange(1,17).reshape(4,4)
print(np.sum(arr2, axis=0))
print(np.sum(arr2, axis=1))


[28 32 36 40]
[10 26 42 58]


Task4

In [24]:
arr = np.random.randint(1,30, size =(5,5))

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))
print("Variance:", np.var(arr))

Mean: 15.76
Median: 17.0
Std Dev: 8.080990038355448
Variance: 65.30239999999999


Task5

In [25]:
arr = np.arange(1, 10).reshape(3, 3)
normalized = (arr - arr.mean()) / arr.std()
print(normalized)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [26]:
arr1 = np.random.randint(1,20, size = (3,3))
arr2 = np.array([1,2,3])
print(arr1 + arr2)

[[ 6 20 18]
 [17 11  5]
 [ 5  3  4]]


In [30]:
arr = np.random.randint(1, 50, size=(4, 4))
vec = np.array([1, 2, 3, 4])

print(arr - vec.reshape(1,4))

[[14 -1 21 13]
 [ 9 31 46 16]
 [41 11 42 33]
 [25 38  5 32]]


Task6

In [34]:
m = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])
print("Determinant:", np.linalg.det(m))
print("Inverse:\n", np.linalg.inv(m))
print("Eigenvalues:", np.linalg.eigvals(m))

Determinant: -1.0
Inverse:
 [[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]
Eigenvalues: [ 3.91222918+0.j  1.28646207+0.j -0.19869124+0.j]


Task7

In [39]:
arr = np.arange(1,10).reshape(1,9)
print(arr)
print(arr.reshape(9,1))

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [44]:
arr = np.random.randint(10, size = (5,5))

arr2 = arr.flatten()
print(arr2)

print(arr2.reshape(5,5))


[1 0 5 4 7 1 3 0 5 4 4 0 2 3 2 0 5 3 4 3 3 2 2 8 6]
[[1 0 5 4 7]
 [1 3 0 5 4]
 [4 0 2 3 2]
 [0 5 3 4 3]
 [3 2 2 8 6]]


Task8

In [45]:
arr = np.random.randint(1, 20, size=(5, 5))
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]   
print(arr)
print("Corners:", corners)

[[17 12 13 17  9]
 [ 9 16 14 15 11]
 [12  3  2  1 10]
 [ 5  8 19 17  5]
 [ 8  8 18  8  9]]
Corners: [17  9  8  9]


In [48]:
arr1 = np.random.randint(1,30, size=(4,4))
print(arr1)
arr[arr > 10 ] = 10
print(arr)

[[10 26 16 14]
 [25 22 24  6]
 [20 21 18 29]
 [ 4 29 22 24]]
[[10 10 10 10  9]
 [ 9 10 10 10 10]
 [10  3  2  1 10]
 [ 5  8 10 10  5]
 [ 8  8 10  8  9]]


Task9

In [49]:
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
data = np.array([('Ali', 25, 70.5),
                 ('Sara', 22, 55.2),
                 ('Ahmed', 30, 80.1),
                 ('Fatima', 19, 60.0)], dtype=dt)
print(np.sort(data, order='age'))

[('Fatima', 19, 60. ) ('Sara', 22, 55.2) ('Ali', 25, 70.5)
 ('Ahmed', 30, 80.1)]


In [50]:
dt = np.dtype([('x', int), ('y', int)])
pts = np.array([(0, 0), (3, 4), (6, 8), (1, 1)], dtype=dt)
n = len(pts)
for i in range(n):
    for j in range(i + 1, n):
        dx = pts['x'][i] - pts['x'][j]
        dy = pts['y'][i] - pts['y'][j]
        d = np.sqrt(dx**2 + dy**2)
        print("point", i, "and point", j, "->", d)

point 0 and point 1 -> 5.0
point 0 and point 2 -> 10.0
point 0 and point 3 -> 1.4142135623730951
point 1 and point 2 -> 5.0
point 1 and point 3 -> 3.605551275463989
point 2 and point 3 -> 8.602325267042627


Task10

In [51]:
a = np.random.randint(1, 21, (4, 4))
print(a)
m = np.ma.masked_greater(a, 10)
print(m)
print("sum:", m.sum())

[[17  5 17 14]
 [20 15 12 10]
 [12  6 10 14]
 [13 15  9 19]]
[[-- 5 -- --]
 [-- -- -- 10]
 [-- 6 10 --]
 [-- -- 9 --]]
sum: 40


In [52]:
a = np.random.randint(1, 21, (3, 3)).astype(float)
mask = np.zeros((3, 3), dtype=bool)
for i in range(3):
    mask[i, i] = True   # mask the diagonal
m = np.ma.masked_array(a, mask=mask)
avg = m.mean()
print(m)
print("mean of unmasked:", avg)
print(m.filled(avg))

[[-- 9.0 5.0]
 [8.0 -- 2.0]
 [14.0 11.0 --]]
mean of unmasked: 8.166666666666666
[[ 8.16666667  9.          5.        ]
 [ 8.          8.16666667  2.        ]
 [14.         11.          8.16666667]]
