# Module: NumPy Assignments (Solved)
## Lesson: NumPy

Har assignment ke solutions neeche diye gaye hain. Reproducible results ke liye random seed set kiya gaya hai.

In [1]:
import numpy as np
np.random.seed(42)   # same results har run par

---
### Assignment 1: Array Creation and Manipulation

**Q1.** (5, 5) random integers (1–20), phir third column ko 1 se replace karo.

In [2]:
arr = np.random.randint(1, 21, size=(5, 5))   # high exclusive, is liye 21
print("Original:\n", arr)

arr[:, 2] = 1      # third column = index 2
print("\nThird column replaced with 1:\n", arr)

Original:
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]

Third column replaced with 1:
 [[ 7 20  1 11  8]
 [ 7 19  1 11  4]
 [ 8  3  1 12  6]
 [ 2  1  1 12 17]
 [10 16  1 15 19]]


**Q2.** (4, 4) array (1 se 16), diagonal ko 0 karo.

In [3]:
arr = np.arange(1, 17).reshape(4, 4)
print("Original:\n", arr)

np.fill_diagonal(arr, 0)
print("\nDiagonal replaced with 0:\n", arr)

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal replaced with 0:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


---
### Assignment 2: Array Indexing and Slicing

**Q1.** (6, 6) array (1–36), 3rd–5th rows aur 2nd–4th columns ka sub-array.

In [4]:
arr = np.arange(1, 37).reshape(6, 6)
print("Array:\n", arr)

sub = arr[2:5, 1:4]   # rows 3-5 => index 2:5, cols 2-4 => index 1:4
print("\nSub-array (rows 3-5, cols 2-4):\n", sub)

Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub-array (rows 3-5, cols 2-4):
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


**Q2.** (5, 5) random array, border ke elements extract karo.

In [5]:
arr = np.random.randint(1, 100, size=(5, 5))
print("Array:\n", arr)

# Method 1: border elements ek 1D array me
border = np.concatenate([arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]])
print("\nBorder elements (1D):", border)

# Method 2: boolean mask se (interior ko hata kar)
mask = np.ones(arr.shape, dtype=bool)
mask[1:-1, 1:-1] = False
print("Border via mask      :", arr[mask])
print("\nBorder only (interior = 0):\n", np.where(mask, arr, 0))

Array:
 [[55 64  3 51  7]
 [21 73 39 18  4]
 [89 60 14  9 90]
 [53  2 84 92 60]
 [71 44  8 47 35]]

Border elements (1D): [55 64  3 51  7 71 44  8 47 35 21 89 53  4 90 60]
Border via mask      : [55 64  3 51  7 21  4 89 90 53 60 71 44  8 47 35]

Border only (interior = 0):
 [[55 64  3 51  7]
 [21  0  0  0  4]
 [89  0  0  0 90]
 [53  0  0  0 60]
 [71 44  8 47 35]]


---
### Assignment 3: Array Operations

**Q1.** Do (3, 4) random arrays par element-wise +, −, ×, ÷.

In [6]:
a = np.random.randint(1, 10, size=(3, 4))
b = np.random.randint(1, 10, size=(3, 4))   # 1 se start taake division by zero na ho
print("A:\n", a, "\n\nB:\n", b)

print("\nAddition:\n", a + b)
print("\nSubtraction:\n", a - b)
print("\nMultiplication:\n", a * b)
print("\nDivision:\n", np.round(a / b, 3))

A:
 [[1 4 2 8]
 [4 2 6 6]
 [4 6 2 2]] 

B:
 [[4 8 7 9]
 [8 5 2 5]
 [8 9 9 1]]

Addition:
 [[ 5 12  9 17]
 [12  7  8 11]
 [12 15 11  3]]

Subtraction:
 [[-3 -4 -5 -1]
 [-4 -3  4  1]
 [-4 -3 -7  1]]

Multiplication:
 [[ 4 32 14 72]
 [32 10 12 30]
 [32 54 18  2]]

Division:
 [[0.25  0.5   0.286 0.889]
 [0.5   0.4   3.    1.2  ]
 [0.5   0.667 0.222 2.   ]]


**Q2.** (4, 4) array (1–16), row-wise aur column-wise sum.

In [7]:
arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr)
print("\nRow-wise sum   (axis=1):", arr.sum(axis=1))
print("Column-wise sum (axis=0):", arr.sum(axis=0))

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum   (axis=1): [10 26 42 58]
Column-wise sum (axis=0): [28 32 36 40]


---
### Assignment 4: Statistical Operations

**Q1.** (5, 5) random array ka mean, median, std, variance.

In [8]:
arr = np.random.randint(1, 50, size=(5, 5))
print("Array:\n", arr)
print("\nMean              :", np.mean(arr))
print("Median            :", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance          :", np.var(arr))

Array:
 [[25  7  9 24  1]
 [44  8 24 11 17]
 [ 8 35 35 33  5]
 [42 39 41 28  7]
 [ 9  8 12 34 33]]

Mean              : 21.56
Median            : 24.0
Standard Deviation: 13.65014285639531
Variance          : 186.32639999999995


**Q2.** (3, 3) array (1–9) ko normalize karo (mean 0, std 1) — Z-score: `(x - mean) / std`.

In [9]:
arr = np.arange(1, 10).reshape(3, 3)
normalized = (arr - arr.mean()) / arr.std()

print("Original:\n", arr)
print("\nNormalized:\n", np.round(normalized, 4))
print("\nCheck -> mean:", round(normalized.mean(), 10), "| std:", round(normalized.std(), 10))

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized:
 [[-1.5492 -1.1619 -0.7746]
 [-0.3873  0.      0.3873]
 [ 0.7746  1.1619  1.5492]]

Check -> mean: 0.0 | std: 1.0


---
### Assignment 5: Broadcasting

**Q1.** (3, 3) array ki har row me shape (3,) ka 1D array add karo.

In [10]:
arr = np.random.randint(1, 10, size=(3, 3))
row = np.array([10, 20, 30])

print("2D array:\n", arr)
print("\n1D array:", row)
print("\nResult (added to each row):\n", arr + row)

2D array:
 [[7 7 8]
 [5 3 8]
 [6 3 1]]

1D array: [10 20 30]

Result (added to each row):
 [[17 27 38]
 [15 23 38]
 [16 23 31]]


**Q2.** (4, 4) array me se shape (4,) ka 1D array har column se subtract karo.

> Note: "har column se subtract" ka matlab hai ke 1D array ko column vector bana kar (`[:, np.newaxis]`) subtract kiya jaye. Row-wise version bhi neeche dikhaya hai.

In [11]:
arr = np.random.randint(10, 50, size=(4, 4))
vec = np.array([1, 2, 3, 4])

print("2D array:\n", arr)
print("\n1D array:", vec)

# Har column me se vec subtract (vec ko column vector banao: shape (4,1))
print("\nSubtract from each column:\n", arr - vec[:, np.newaxis])

# Alternative: har row me se subtract (default broadcasting)
print("\n(Alternative) Subtract from each row:\n", arr - vec)

2D array:
 [[44 46 23 12]
 [10 14 35 23]
 [48 36 18 24]
 [24 35 22 41]]

1D array: [1 2 3 4]

Subtract from each column:
 [[43 45 22 11]
 [ 8 12 33 21]
 [45 33 15 21]
 [20 31 18 37]]

(Alternative) Subtract from each row:
 [[43 44 20  8]
 [ 9 12 32 19]
 [47 34 15 20]
 [23 33 19 37]]


---
### Assignment 6: Linear Algebra

**Q1.** (3, 3) matrix ka determinant, inverse, eigenvalues.

In [12]:
M = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])
print("Matrix:\n", M)

det = np.linalg.det(M)
print("\nDeterminant:", round(det, 4))

if not np.isclose(det, 0):
    inv = np.linalg.inv(M)
    print("\nInverse:\n", np.round(inv, 4))
    print("\nVerify M @ inv = I:\n", np.round(M @ inv, 4))
else:
    print("Matrix singular hai, inverse exist nahi karta.")

eigvals = np.linalg.eigvals(M)
print("\nEigenvalues:", np.round(eigvals, 4))

Matrix:
 [[2 1 1]
 [1 3 2]
 [1 0 0]]

Determinant: -1.0

Inverse:
 [[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]

Verify M @ inv = I:
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]

Eigenvalues: [ 3.9122  1.2865 -0.1987]


**Q2.** (2, 3) aur (3, 2) arrays ka matrix multiplication.

In [13]:
A = np.random.randint(1, 10, size=(2, 3))
B = np.random.randint(1, 10, size=(3, 2))
print("A (2x3):\n", A, "\n\nB (3x2):\n", B)

result = np.dot(A, B)       # ya A @ B
print("\nA @ B (2x2):\n", result)

A (2x3):
 [[7 1 4]
 [4 5 7]] 

B (3x2):
 [[7 4]
 [7 3]
 [6 2]]

A @ B (2x2):
 [[ 80  39]
 [105  45]]


---
### Assignment 7: Advanced Array Manipulation

**Q1.** (3, 3) array (1–9) ko (1, 9) aur phir (9, 1) me reshape karo.

In [14]:
arr = np.arange(1, 10).reshape(3, 3)
print("Original (3,3):\n", arr)

r1 = arr.reshape(1, 9)
print("\nReshaped (1,9):\n", r1, "\nShape:", r1.shape)

r2 = r1.reshape(9, 1)
print("\nReshaped (9,1):\n", r2, "\nShape:", r2.shape)

Original (3,3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped (1,9):
 [[1 2 3 4 5 6 7 8 9]] 
Shape: (1, 9)

Reshaped (9,1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 
Shape: (9, 1)


**Q2.** (5, 5) random array ko flatten karo, phir wapas (5, 5) me reshape karo.

In [15]:
arr = np.random.randint(1, 100, size=(5, 5))
print("Original:\n", arr)

flat = arr.flatten()
print("\nFlattened:", flat, "| shape:", flat.shape)

back = flat.reshape(5, 5)
print("\nReshaped back (5,5):\n", back)
print("\nSame as original?", np.array_equal(arr, back))

Original:
 [[42 45 62 57  6]
 [28 28 44 84 30]
 [62 75 92 89 62]
 [97  1 27 62 77]
 [ 3 70 72 27  9]]

Flattened: [42 45 62 57  6 28 28 44 84 30 62 75 92 89 62 97  1 27 62 77  3 70 72 27
  9] | shape: (25,)

Reshaped back (5,5):
 [[42 45 62 57  6]
 [28 28 44 84 30]
 [62 75 92 89 62]
 [97  1 27 62 77]
 [ 3 70 72 27  9]]

Same as original? True


---
### Assignment 8: Fancy Indexing and Boolean Indexing

**Q1.** (5, 5) random array ke corners fancy indexing se nikalo.

In [16]:
arr = np.random.randint(1, 100, size=(5, 5))
print("Array:\n", arr)

rows = np.array([0, 0, -1, -1])
cols = np.array([0, -1, 0, -1])
print("\nCorners (TL, TR, BL, BR):", arr[rows, cols])

Array:
 [[62 37 97 51 44]
 [24 79 59 32 96]
 [88 52 62 58 52]
 [12 39  2  3 56]
 [81 59  2  2 92]]

Corners (TL, TR, BL, BR): [62 44 81 92]


**Q2.** (4, 4) random array me 10 se bade elements ko boolean indexing se 10 set karo.

In [17]:
arr = np.random.randint(1, 21, size=(4, 4))
print("Original:\n", arr)

arr[arr > 10] = 10
print("\nAfter capping at 10:\n", arr)

Original:
 [[ 5  1  1 19]
 [ 2 12  6  4]
 [11 17  6  5]
 [20  2  6 11]]

After capping at 10:
 [[ 5  1  1 10]
 [ 2 10  6  4]
 [10 10  6  5]
 [10  2  6 10]]


---
### Assignment 9: Structured Arrays

**Q1.** Fields `name`, `age`, `weight` ke saath structured array banao aur age ke hisaab se sort karo.

In [18]:
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
people = np.array([('Ali',   25, 70.5),
                   ('Sara',  22, 55.2),
                   ('Ahmed', 30, 82.0),
                   ('Maryam',21, 58.3),
                   ('Usman', 27, 75.1)], dtype=dtype)

print("Original:\n", people)

sorted_people = np.sort(people, order='age')
print("\nSorted by age:\n", sorted_people)

Original:
 [('Ali', 25, 70.5) ('Sara', 22, 55.2) ('Ahmed', 30, 82. )
 ('Maryam', 21, 58.3) ('Usman', 27, 75.1)]

Sorted by age:
 [('Maryam', 21, 58.3) ('Sara', 22, 55.2) ('Ali', 25, 70.5)
 ('Usman', 27, 75.1) ('Ahmed', 30, 82. )]


**Q2.** Fields `x`, `y` (integers); har pair of points ke beech Euclidean distance.

In [19]:
pts = np.array([(0, 0), (3, 4), (6, 8), (1, 1)], dtype=[('x', 'i4'), ('y', 'i4')])
print("Points:\n", pts)

x, y = pts['x'].astype(float), pts['y'].astype(float)

# Broadcasting se pairwise distance matrix
dx = x[:, None] - x[None, :]
dy = y[:, None] - y[None, :]
dist = np.sqrt(dx**2 + dy**2)
print("\nPairwise Euclidean distance matrix:\n", np.round(dist, 3))

# Pairs ki list
print()
n = len(pts)
for i in range(n):
    for j in range(i + 1, n):
        print(f"Point {i} ({x[i]:.0f},{y[i]:.0f}) <-> Point {j} ({x[j]:.0f},{y[j]:.0f}) : {dist[i, j]:.3f}")

Points:
 [(0, 0) (3, 4) (6, 8) (1, 1)]

Pairwise Euclidean distance matrix:
 [[ 0.     5.    10.     1.414]
 [ 5.     0.     5.     3.606]
 [10.     5.     0.     8.602]
 [ 1.414  3.606  8.602  0.   ]]

Point 0 (0,0) <-> Point 1 (3,4) : 5.000
Point 0 (0,0) <-> Point 2 (6,8) : 10.000
Point 0 (0,0) <-> Point 3 (1,1) : 1.414
Point 1 (3,4) <-> Point 2 (6,8) : 5.000
Point 1 (3,4) <-> Point 3 (1,1) : 3.606
Point 2 (6,8) <-> Point 3 (1,1) : 8.602


---
### Assignment 10: Masked Arrays

**Q1.** (4, 4) masked array, 10 se bade elements mask karo, unmasked elements ka sum.

In [20]:
data = np.random.randint(1, 21, size=(4, 4))
masked = np.ma.masked_greater(data, 10)

print("Original:\n", data)
print("\nMasked array:\n", masked)
print("\nSum of unmasked elements:", masked.sum())

Original:
 [[16 16  1  9]
 [ 6 16  3 20]
 [ 4 19  3 19]
 [20  7 20  9]]

Masked array:
 [[-- -- 1 9]
 [6 -- 3 --]
 [4 -- 3 --]
 [-- 7 -- 9]]

Sum of unmasked elements: 42


**Q2.** (3, 3) masked array, diagonal mask karo, masked elements ko unmasked ke mean se replace karo.

In [21]:
data = np.random.randint(1, 20, size=(3, 3))
mask = np.eye(3, dtype=bool)                 # diagonal True
masked = np.ma.array(data, mask=mask)

print("Original:\n", data)
print("\nMasked (diagonal hidden):\n", masked)

mean_val = masked.mean()
print("\nMean of unmasked elements:", round(float(mean_val), 4))

replaced = masked.filled(mean_val)
print("\nMasked elements replaced with mean:\n", np.round(replaced, 2))

Original:
 [[ 1  8  7]
 [18  8  1]
 [11 18 10]]

Masked (diagonal hidden):
 [[-- 8 7]
 [18 -- 1]
 [11 18 --]]

Mean of unmasked elements: 10.5

Masked elements replaced with mean:
 [[10  8  7]
 [18 10  1]
 [11 18 10]]
